### ISSUE TITLE
Image credits

### ISSUE THREAD

**Issue by COLLIER72** [COLLIER72/COLLIER72#14]
Need to add more spots for image credits.

**Comment by arena** [comment]
I'm not sure how to do this via the database. I could figure it out with some time, but in the interim I can hard code the full list of photographers with links. (that will also solve the punctuation and spacing issues that are bugging me about the way the credits look)

**Comment by arena** [comment]
I'm closing this issue. I left a note in the CMS letting anybody who uses it (or who forks this project) that the photo credits are coming directly from the view file instead of the database.
