### ISSUE TITLE
Maps & Updates Emergency Line

### ISSUE THREAD

**Issue by COLLIER72** [COLLIER72/COLLIER72#5]
Try and see if we could shrink the "In an emergency..." box so the orange doesn't take up as much "map" space.

**Comment by arena** [comment]
How do you feel about the "Map Guide" ...maybe we could take that out? It actually has some issues like, calling the official updates tweets "crowd sourced updates". 

I suggest removing the tour link and then shortening the copy.

Copy Edit:
Let's leave the title as is
"In an emergency, this page will be your real-time information hub."

but then shorten the copy below...

from:
You’ll find official updates, crowdsourced reports, and a crisis map to navigate county resources. Tour this Emergency Mode to better understand how to use it in the event of an emergency.

to:
You’ll find useful twitter feeds and a crisis map to help you navigate county resources in the event of an emergency.

**Comment by COLLIER72** [comment]
Let me think about, however I do agree with just having a statement with no links.

Sent from my iPhone

On May 21, 2015, at 7:42 PM, Arena <notifications@github.com<mailto:notifications@github.com>> wrote:

How do you feel about the "Map Guide" ...I maybe we could take that out? It actually has some issues like, calling the official updates tweets "crowd sourced updates". Ok with me taking out that link?

Under
In an emergency, this page will be your real-time information hub.

We could shorten the copy from:
You’ll find official updates, crowdsourced reports, and a crisis map to navigate county resources. Tour this Emergency Mode to better understand how to use it in the event of an emergency.

to:
You’ll find useful twitter feeds and a crisis map to help you navigate county resources in the event of an emergency.

**Comment by arena** [comment]
I think keeping the 'expand map' link is nice and it visually balances the message box.

**Comment by arena** [comment]
keep in mind that this area will contain much more relevant information if you switch to emergency mode (e.g. "Storm-Name Expected on Date" followed by "Important detail about this storm.")

**Comment by arena** [comment]
I'll take out the one link and shorten the text for starters. We can always take out more if you want it to shrink more. Shortening now. :)

**Comment by COLLIER72** [comment]
You'll find official twitter updates and a crisis map to help you see potential county emergency information. Note: We cannot guarantee the completeness of the information.

What you think?

**Comment by arena** [comment]
before
![image](https://cloud.githubusercontent.com/assets/411070/7778261/85e7a62c-007e-11e5-9e60-362b0825510e.png)

after
![image](https://cloud.githubusercontent.com/assets/411070/7778266/9181187e-007e-11e5-9bf8-d48d03671465.png)

I think that's about as skinny as it gets for now.

We could possibly shave away the subtitle, but that might mess up the Emergency Mode styling.

**Comment by COLLIER72** [comment]
Looks good.

**Comment by arena** [comment]
Yay!! It will be deployed shortly. :)
