### ISSUE TITLE
Stories, adjust amount

### ISSUE THREAD

**Issue by COLLIER72** [COLLIER72/COLLIER72#7]
Allow for less or more than four stories to show up on the page.

**Comment by arena** [comment]
I don't have the expertise to implement a feature that changes the layout based on the number of stories added. However, I can comment out a couple of the stories and then we can add them back later.

**Comment by COLLIER72** [comment]
What I could do is a "Coming Soon" slot. Should be relatively easy?

**Comment by arena** [comment]
For now, there are only two stories showing on the View Stories pg. 
To switch it back to 4 (or the number of stories that have records in the database to be more precise) change the stories_controller.rb file. I put a comment in the file.

![image](https://cloud.githubusercontent.com/assets/411070/7894685/64cbda58-0623-11e5-90b3-39f54a2f0e63.png)

that part that says ".slice(0,2)" ...just delete it and save the file. When you redeploy you will see 4 stories.

NOTE: in the interim you'll still see 4 stories in the CMS, which is kinda nice, you can add local stories before you re-show them on the live site.
