### ISSUE TITLE
MIT License

### ISSUE THREAD

**Issue by arena** [COLLIER72/COLLIER72#9]
Since this GitHub project is public, and a very nice starting place for other counties, it should have a license file so that it's clear how people can use it and that it is available "as is"

City72 has a license.md file that is the boiler plate of the MIT license ..I suggest we copy it over. ..Normally, if we were doing development in an ideal world, we'd sync with City72 but we've edited so much hard-coded stuff that we need to pick and choose. 

This project is essentially "County72"

**Comment by COLLIER72** [comment]
Do as needed.

**Comment by arena** [comment]
done.
